services:
  postgres:
    image: postgres:15
    container_name: resume-postgres
    restart: always
    # Local dev: values come from .env; Prod (GCP): inject env vars via your deployment
    env_file:
      - apps/backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-resume_app}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: resume-redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: resume-minio
    command: server /data --console-address ":9001"
    # Local dev: values come from .env; Prod (GCP): inject env vars via your deployment
    env_file:
      - apps/backend/.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO web console
    volumes:
      - minio_data:/data

  pdf-parser:
    build:
      context: ./pdf-parser-service
      dockerfile: Dockerfile
    container_name: resume-pdf-parser
    restart: always
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: resume-backend
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
      - pdf-parser
    env_file:
      - apps/backend/.env
    environment:
      PORT: ${PORT:-5000}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-ai-resume}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PDF_PARSER_SERVICE_URL: ${PDF_PARSER_SERVICE_URL:-http://pdf-parser:8000}
    ports:
      - "5000:5000"

volumes:
  pgdata:
  minio_data:
